apiVersion: apps/v1
kind: Deployment
metadata:
  name: wgr
spec:
  selector:
    matchLabels:
      app: wgr
      tier: backend
      track: stable
  replicas: 7
  template:
    metadata:
      labels:
        app: wgr
        tier: backend
        track: stable
    spec:
      containers:
        - name: wgr
          image: "TO BE FILLED IN LATER"
          ports:
            - name: http
              containerPort: 80
